# Задания

1. Реализовать класс Matrix (матрица). Обеспечить перегрузку конструктора класса (метод __init__()), который должен принимать данные (список списков) для формирования матрицы.

    Подсказка: матрица — система некоторых математических величин, расположенных в виде прямоугольной схемы.
    Примеры матриц: 3 на 2, 3 на 3, 2 на 4.
<pre>
    31    32         3    5    32        3    5    8    3
    37    43         2    4    6         8    3    7    1
    51    86        -1   64   -8
</pre>
    Следующий шаг — реализовать перегрузку метода __str__() для вывода матрицы в привычном виде.
    Далее реализовать перегрузку метода __add__() для реализации операции сложения двух объектов класса Matrix (двух матриц). Результатом сложения должна быть новая матрица.

    Подсказка: сложение элементов матриц выполнять поэлементно — первый элемент первой строки первой матрицы складываем с первым элементом первой строки второй матрицы и т.д.
    
2. Реализовать проект расчёта суммарного расхода ткани на производство одежды. Основная сущность (класс) этого проекта — одежда, которая может иметь определённое название. К типам одежды в этом проекте относятся пальто и костюм. У этих типов одежды существуют параметры: размер (для пальто) и рост (для костюма). Это могут быть обычные числа: V и H, соответственно.

    Для определения расхода ткани по каждому типу одежды использовать формулы: для пальто (V/6.5 + 0.5), для костюма (2*H + 0.3). Проверить работу этих методов на реальных данных.
    Реализовать общий подсчет расхода ткани. Проверить на практике полученные на этом уроке знания: реализовать абстрактные классы для основных классов проекта, проверить на практике работу декоратора @property.
    
3. Реализовать программу работы с органическими клетками, состоящими из ячеек. Необходимо создать класс Клетка. В его конструкторе инициализировать параметр, соответствующий количеству ячеек клетки (целое число). В классе должны быть реализованы методы перегрузки арифметических операторов: сложение (__add__()), вычитание (__sub__()), умножение (__mul__()), деление (__truediv__()). Данные методы должны применяться только к клеткам и выполнять увеличение, уменьшение, умножение и целочисленное (с округлением до целого) деление клеток, соответственно.

    Сложение. Объединение двух клеток. При этом число ячеек общей клетки должно равняться сумме ячеек исходных двух клеток.
    
    Вычитание. Участвуют две клетки. Операцию необходимо выполнять только если разность количества ячеек двух клеток больше нуля, иначе выводить соответствующее сообщение.
    
    Умножение. Создаётся общая клетка из двух. Число ячеек общей клетки определяется как произведение количества ячеек этих двух клеток.
    
    Деление. Создаётся общая клетка из двух. Число ячеек общей клетки определяется как целочисленное деление количества ячеек этих двух клеток.
    
    В классе необходимо реализовать метод make_order(), принимающий экземпляр класса и количество ячеек в ряду. Данный метод позволяет организовать ячейки по рядам.
    
    Метод должен возвращать строку вида \*\*\*\*\*\n\*\*\*\*\*\n\*\*\*\*\*..., где количество ячеек между \n равно переданному аргументу. Если ячеек на формирование ряда не хватает, то в последний ряд записываются все оставшиеся.

    Например, количество ячеек клетки равняется 12, количество ячеек в ряду — 5. Тогда метод make_order() вернёт строку: \*\*\*\*\*\n\*\*\*\*\*\n\*\*.
    
    Или, количество ячеек клетки равняется 15, количество ячеек в ряду — 5. Тогда метод make_order() вернёт строку: \*\*\*\*\*\n\*\*\*\*\*\n\*\*\*\*\*.
    
    Подсказка: подробный список операторов для перегрузки доступен по ссылке.

# Задача 1

## Вариант 1

In [1]:
import numpy as np
class Matrix():
    def __init__(self,list_number=None,list_length=None):
        self.list_number = list_number
        self.list_length = list_length
        Matrix.matrix_gen(self)

    def matrix_gen(self):
        if not self.list_number and not self.list_length:
            self.list_number = int(input('Укажите количество списков: '))
            self.list_length = int(input('Укажите длину списков: '))
        self.matrix = np.zeros([self.list_number,self.list_length])
        for k,row in enumerate(self.matrix):
            for i in range(len(row)):
                row[i] = np.random.randint(0,100)

    def __str__(self):
        return f'{self.matrix}'
    def __add__(self,other):
        self.added = []
        for k,i in enumerate(self.matrix):
            self.added.append([])
            for kk,j in enumerate(i):
                self.added[k].append(self.matrix[k][kk]+other[k][kk])
                
        return np.array(self.added)

print('''
Данная программа генерирует две матрицы одинакового размера, заданного пользователем;
После генерации и вывода сгенерированных матриц на экран,
производится суммирование двух матриц,
результирующая матрица также выводится на экран.
''')
get_matrix = Matrix()
print('Первая матрица:')
print(get_matrix.matrix)
x = get_matrix.matrix.shape[0]
y = get_matrix.matrix.shape[1]
get_matrix2 = Matrix(x,y)
print('\nВторая матрица:')
print(get_matrix2.matrix)
print('\nСумма двух матриц:')
print(get_matrix+get_matrix2.matrix)


Данная программа генерирует две матрицы одинакового размера, заданного пользователем;
После генерации и вывода сгенерированных матриц на экран,
производится суммирование двух матриц,
результирующая матрица также выводится на экран.



Укажите количество списков:  7
Укажите длину списков:  12


Первая матрица:
[[51.  5. 68. 93. 36. 44.  9. 63. 28. 43. 65. 22.]
 [59. 46. 40. 56. 63. 74. 28. 46. 49. 93. 85. 34.]
 [98. 93. 44. 81. 36. 19. 44. 76. 61. 19. 88. 26.]
 [30. 32. 53. 87. 20. 69. 11. 64. 62. 91. 94. 97.]
 [18. 78. 48. 47. 81. 43. 71. 96. 46.  2. 18. 19.]
 [82. 28. 71.  3. 52. 12. 69.  6. 37. 17. 53. 44.]
 [71. 59. 86.  1. 40. 40. 59.  2. 19. 95. 10. 65.]]

Вторая матрица:
[[56. 55. 50. 24. 44. 41. 68. 38. 17. 63. 10. 37.]
 [27. 93. 65. 43. 54. 48. 85. 33. 64. 75. 68. 28.]
 [39. 46. 75. 58. 54. 26. 21. 31. 83. 34. 20. 27.]
 [36. 54. 51. 43. 64. 76. 96. 72. 66. 24. 67. 22.]
 [95. 38. 53. 46. 93. 90. 10. 40. 63. 16. 21. 37.]
 [51. 46. 41. 94. 50. 44. 76.  5. 48. 44. 10. 39.]
 [73. 44.  3. 25. 48. 58. 86. 86.  1.  2. 71. 74.]]

Сумма двух матриц:
[[107.  60. 118. 117.  80.  85.  77. 101.  45. 106.  75.  59.]
 [ 86. 139. 105.  99. 117. 122. 113.  79. 113. 168. 153.  62.]
 [137. 139. 119. 139.  90.  45.  65. 107. 144.  53. 108.  53.]
 [ 66.  86. 104. 130.  84. 145. 107. 136. 

## Вариант 2

In [2]:
import numpy as np
class Matrix():
    def __init__(self,list1,list2):
        self.list1 = list1
        self.list2 = list2

    def matrix_gen(self):
        self.matrix = np.zeros([len(self.list1),2])
        for k,row in enumerate(self.matrix):
            row[0],row[1] = self.list1[k],self.list2[k]
            

    def __str__(self):
        return f'{self.matrix}'
    
    def __add__(self,other):
        self.added = []
        for k,i in enumerate(self.matrix):
            self.added.append([])
            for kk,j in enumerate(i):
                self.added[k].append(self.matrix[k][kk]+other[k][kk])
                
        return np.array(self.added)




list1 = [1,2,3]
list2 = [4,5,6]
get_matrix = Matrix(list1,list2)
get_matrix.matrix_gen()
print(get_matrix.matrix)
get_matrix2 = Matrix(list1,list2)
get_matrix2.matrix_gen()
print(get_matrix2.matrix)
print(get_matrix+get_matrix2.matrix)

[[1. 4.]
 [2. 5.]
 [3. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]
[[ 2.  8.]
 [ 4. 10.]
 [ 6. 12.]]


# Задача 2

In [3]:
class cloth():
    cloth_name = input('Введите 1, если Вам нужно пальто; 2, если нужен костюм: ')
    cloth_dict = {'1':'coat','2':'suite'}
    cloth_name = cloth_dict[cloth_name]
    param = None
    while not param:
        try:
            param = float(input('Укажите размер пальто или рост для костюма (только цифры): '))
        except Exception:
            print('Исправьте, пожалуйста, ошибку ввода данных: для указания размера или роста можно использовать только цифры.')
            param = None
                    
    def __init__(self,cloth_name=cloth_name,param=param):
        self.name=cloth_name
        self.param = param
        self.size,self.height = None,None
        
    def features(self):
        if str(self.param).replace('.','',1).isdigit():
            if self.name == 'coat':
                self.size = self.param
            elif self.name == 'suite':
                self.height = self.param
            else:
                return f'Проверьте использованные параметры - и попробуйте еще раз.'
        else:
            return 'Проверьте значения параметров - и попробуйте еще раз.'
    @property
    def material_amount(self):
        cloth.features(self)
        if self.size:
            self.amount = self.size/6 +0.5
        if self.height:
            self.amount = 2*self.height + 0.3
        return self.amount



material_amount = cloth()
material_amount.material_amount

Введите 1, если Вам нужно пальто; 2, если нужен костюм:  2
Укажите размер пальто или рост для костюма (только цифры):  1.8


3.9

# Задача 3

In [7]:
class Cell():
    def __init__(self,cells):
        self.cells=cells
    
    def __add__(self,second):
        return self.cells+2*second.cells
    
    def __sub__(self,second):
        return max(self.cells,second.cells)-min(self.cells,second.cells) if self.cells!=second.cells else 'клетки одинакового размера'
    
    def __mul__(self,second):
        return max(self.cells,second.cells)*min(self.cells,second.cells)
    
    def __truediv__(self,second):
        return max(self.cells,second.cells)//min(self.cells,second.cells)
    
    def make_order(self,in_row):
        rows = self.cells//in_row
        last_row = self.cells%in_row
        result = ['*'*in_row]*rows
        if last_row>0:
            result.append('*'*last_row)
        return print(*result,sep='\n')

first = None
second = None
while not first or not second:
    try:
        first = int(input('Укажите количество ячеек в первой клетке: '))
        second = int(input('Укажите количество ячеек во второй клетке: '))
    except Exception:
        print('Нужно ввести числовые значения для указания количества ячеек.')
        first = None
        second = None
a = Cell(first)
b = Cell(second)
print(Cell(a.cells)+Cell(b.cells))
print(Cell(a.cells)-Cell(b.cells))
print(Cell(a.cells)*Cell(b.cells))
print(Cell(a.cells)/Cell(b.cells))

Укажите количество ячеек в первой клетке:  12
Укажите количество ячеек во второй клетке:  5


22
7
60
2


In [8]:
a.make_order(5)

*****
*****
**
